/**
 * polycheck — what this project's agent policy actually permits.
 *
 * Puffin already checks, after a turn, whether a session changed files the card
 * never declared. polycheck answers the stronger question first: does the
 * policy even ALLOW this session to write the check that decides its own gate?
 * If it does, that session's green result is not evidence, and the turn is not
 * worth spending — a distinction no per-action permission prompt can make,
 * because the hazard is a property of accumulated session state.
 *
 * The two are complements, not duplicates. polycheck is prevention and runs
 * before anything happens; the git-based scope check is detection and runs
 * after. A tight policy can still be handed the file some other way, and a
 * loose policy does not mean the session misbehaved.
 *
 * The mandate is generated from the sekkei rather than kept in the repo, which
 * happens to satisfy polycheck's own requirement for it: the declaration is
 * only worth something if it is not something the session can edit.
 *
 * @module polycheck-service
 */

'use strict'

const { spawn } = require('child_process')
const fs = require('fs')
const path = require('path')
const os = require('os')

/** How long a lint may take before we stop waiting. It is normally seconds. */
const TIMEOUT_MS = 60_000

class PolycheckService {
  /**
   * @param {Object} options
   * @param {string|null} [options.projectPath]
   * @param {string|null} [options.polycheckDir] - explicit checkout
   */
  constructor(options = {}) {
    this.projectPath = options.projectPath || null
    this._explicitDir = options.polycheckDir || null
    this._runCommand = options.runCommand || null // injectable for tests
  }

  setProjectPath(projectPath) {
    this.projectPath = projectPath
  }

  /**
   * Locate polycheck: an explicit path, the env var, or a sibling checkout.
   *
   * No npx fallback. Fetching a linter from the network to decide whether a
   * policy is safe is a strange trade, and an offline machine should get a
   * clear "not installed" rather than a hang.
   *
   * @returns {string|null} path to bin/polycheck.mjs
   */
  resolveBin() {
    const candidates = [
      this._explicitDir,
      process.env.POLYCHECK_DIR,
      this.projectPath ? path.resolve(this.projectPath, '..', 'polycheck') : null,
      path.resolve(__dirname, '..', '..', '..', 'polycheck')
    ].filter(Boolean)

    for (const dir of candidates) {
      const bin = path.join(dir, 'bin', 'polycheck.mjs')
      if (fs.existsSync(bin)) return bin
    }
    return null
  }

  /** @returns {{available: boolean, bin: string|null}} */
  getStatus() {
    const bin = this.resolveBin()
    return { available: !!bin, bin }
  }

  /**
   * Write the mandate: what each card declared it would produce.
   *
   * Lives outside the repo, in a temp file, for the same reason polycheck asks
   * for it: a declaration the session can edit proves nothing.
   *
   * @param {Array<{id: string, gloss?: string, outputs: string[]}>} cards
   * @returns {string} path to the mandate file
   */
  writeMandate(cards = []) {
    const dir = path.join(os.tmpdir(), 'puffin-mandate')
    fs.mkdirSync(dir, { recursive: true })
    const file = path.join(dir, `mandate-${path.basename(this.projectPath || 'project')}.json`)
    fs.writeFileSync(file, JSON.stringify({
      version: '0.1.0',
      '//': 'Generated by Puffin from the sekkei. One entry per card: the outputs ' +
        'its prompt spec and acceptance spec declare.',
      mandates: cards.map(card => ({
        id: card.id,
        gloss: card.gloss || card.id,
        outputs: card.outputs || []
      }))
    }, null, 2))
    return file
  }

  /**
   * Run polycheck over the project, optionally against a mandate.
   *
   * @param {{cards?: Array<Object>}} [options]
   * @returns {Promise<Object>}
   */
  async check({ cards } = {}) {
    const bin = this.resolveBin()
    if (!bin) {
      return { success: false, available: false, error: 'polycheck not found (set POLYCHECK_DIR)' }
    }
    if (!this.projectPath) return { success: false, error: 'No project open' }

    const args = [bin, this.projectPath, '--json']
    let mandateFile = null
    if (Array.isArray(cards) && cards.length > 0) {
      mandateFile = this.writeMandate(cards)
      args.push('--mandate', mandateFile)
    }

    try {
      const result = await this._run(args)
      // Exit 1 is a real verdict (bypass or mandate surplus), not a crash — the
      // report on stdout is what matters, and refusing to parse it would throw
      // away the finding the run exists to produce.
      const report = result.stdout.trim() ? JSON.parse(result.stdout) : null
      if (!report) {
        return { success: false, error: result.stderr.trim() || `polycheck exited ${result.code}` }
      }
      return { success: true, available: true, report, verdict: report.verdict, mandate: summarise(report) }
    } catch (error) {
      return { success: false, error: error.message }
    } finally {
      if (mandateFile) { try { fs.rmSync(mandateFile, { force: true }) } catch { /* temp file */ } }
    }
  }

  /** @private */
  _run(args) {
    if (this._runCommand) return this._runCommand(args)
    return new Promise((resolve, reject) => {
      const child = spawn(process.execPath, args, { windowsHide: true })
      let stdout = ''
      let stderr = ''
      const timer = setTimeout(() => {
        child.kill()
        reject(new Error('polycheck timed out'))
      }, TIMEOUT_MS)
      child.stdout.on('data', d => { stdout += d })
      child.stderr.on('data', d => { stderr += d })
      child.on('error', err => { clearTimeout(timer); reject(err) })
      child.on('close', code => { clearTimeout(timer); resolve({ code, stdout, stderr }) })
    })
  }
}

/**
 * Per-card verdicts, in the terms the runner decides on.
 *
 * `oracle` is singled out because it is the one class where a passing gate
 * stops being evidence: the session could have written the check itself.
 * Everything else in SURPLUS is worth showing and not worth stopping for.
 *
 * @param {Object} report - polycheck --json output
 * @returns {Object<string, {status: string, oracle: boolean, paths: string[], reason: string}>}
 */
function summarise(report) {
  const byCard = {}
  for (const result of report?.mandate?.results || []) {
    const surplus = result.surplus || []
    const oracle = surplus.filter(s => s.class === 'oracle')
    byCard[result.id] = {
      status: result.status,
      oracle: oracle.length > 0,
      paths: [...new Set(surplus.map(s => s.path))],
      oraclePaths: [...new Set(oracle.map(s => s.path))],
      reason: result.reason || '',
      fix: result.fix || null
    }
  }
  return byCard
}

module.exports = { PolycheckService, summarise }
